### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by breadbreadbread** [marbink/PoGo-Captcha#2]
Get Nullpixel and hack this together with his Captcha Clicker so i can give this page to my friends and make them solve captchas for me passively.

**Comment by marbink** [comment]
Can you give me more informations about that Captcha Clicker?

**Comment by breadbreadbread** [comment]
https://captcha.nullpixel.uk/

Nullpixel at somepoint made this, I would assume that some sort of system could be made that would allow in-web solving of captchas just as you send them to 2captcha. 

I dont know if its open, or available anywhere. Perhaps if you asked him. I'm sorry I cant offer more help.

Thank you for everything

**Comment by marbink** [comment]
Thank you for the idea. But that's not a praticable way. Seems that servers will accept requests coming from the domain for what the Api Key is registered for.
