### ISSUE TITLE
Working on linux

### ISSUE THREAD

**Issue by nomisunrider** [marbink/PoGo-Captcha#3]
This errors on linux unless you add the path to the chromedriver binary.
For my instance, I had to modify line 147 to this.

                    driver = webdriver.Chrome('node_modules/.bin/chromedriver')

**Comment by Obihoernchen** [comment]
It behaves like it should.
It's your job to set the linux PATH variable or set a link to the binary in /usr/local/bin if you install manually.  Actually newer distributions like Fedora have a chromedriver package which will do the stuff for you.

**Comment by marbink** [comment]
I'm quite agree with @Obihoernchen but I will seriously consider the idea to add a new cli param to set it. Thanks for the feedback!
