### ISSUE TITLE
[Feature Request] Present Captcha to Map Users

### ISSUE THREAD

**Issue by chromer90** [marbink/PoGo-Captcha#4]
I have some programming experience but am a little rusty and by no means fluent in python. I would really love if there was a way to implement this onto my map website and then users of the map would have the option to help solve captcha. Is this even possible to try to implement?

**Comment by marbink** [comment]
The main problem is to include recaptcha in a website. Every recaptcha can be solved only if requests starts from the same domain associated with that api key. For this reason captcha must be solved inside a page with the pgo domain. There should be a way using some tricks but i think that's illegal or at least breaking recaptcha tos.
