### ISSUE TITLE
Attribute Error

### ISSUE THREAD

**Issue by bwoodruff90** [marbink/PoGo-Captcha#7]
python /Users/XXX/Desktop/PoGo-Captcha-master/pogo-captcha.py -a ptc -u XXXX -p XXXX -l '-123.123, 123.123' -hk XXXX -c XXXXX

[ERROR][XXXXX] AttributeError()

**Comment by marbink** [comment]
Try using `-v`. It could print some more informations that could help investigating.

**Comment by bwoodruff90** [comment]
When putting the -  in the front of location -123.000 it is causing the
error

**Comment by marbink** [comment]
Tried pasting your syntax (replacing only XXX with my test data) and leaving the location as it is in your message: no errors. Can you check again please? But please use `-v`.

**Comment by bwoodruff90** [comment]
the issue above was the space & ' ' however similar issue with location still.

Ben$ python /Users/Ben/Desktop/PoGo-Captcha-master/pogo-captcha.py -a ptc -u xxx -p Xxx+ -l -12.462659,130.841546 -c xxxx -v
usage: pogo-captcha.py [-h] [-ac ACCOUNTCSV] [-a AUTH_SERVICE] [-hk HASH_KEY]
                       [-u USERNAME] [-p PASSWORD] -l LOCATION [-px PROXY]
                       [-c CAPTCHAKEY] [-ch CHROMEDIR] [-v]
pogo-captcha.py: error: argument -l/--location: expected one argument

works fine when the - is removed from the -12.4626 however that would be the incorrect location.

**Comment by marbink** [comment]
Yep, parser is doing something weird with location param. Using quotes and space after comma seems to make it work.

**Comment by bwoodruff90** [comment]
ahh you legend ! thank you.
